### PR TITLE
fix: Update helm CRD

### PR DESCRIPTION
**Pull request by simon-cj**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update CRD in helm charts
```

### CODE REVIEW

**Review by FogDong — COMMENTED** [review]
/lgtn

**Comment by simon-cj** [comment]
> /lgtn

Need lgtm, need update it again @FogDong

**Comment by FogDong** [comment]
We are not in the OWNER group...😅   /cc @gaocegege

**Pull request merged**
